// This file is auto-generated by `supabase gen types typescript`.
// DO NOT EDIT MANUALLY. Run `pnpm db:push && supabase gen types typescript > src/types/supabase.ts` to regenerate.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
