name: Auto add to project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to hack1-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.6.1
        with:
          project-url: https://github.com/orgs/chofurenairengo/projects/7
          github-token: ${{ secrets.PROJECT_TOKEN }}
